disabled_rules:
  - trailing_comma
  - weak_delegate

line_length: 
  warning: 120
  error: 120

type_name: 
  max_length:
    warning: 50
    error: 50

file_length:
  warning: 300
  error: 300

nesting:
  type_level:
    warning: 2
    error: 2
